"""player_position and unique position name

Revision ID: 45fcf2f2c14a
Revises: 92b512c5ec7c
Create Date: 2020-08-04 20:06:22.619831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fcf2f2c14a'
down_revision = '92b512c5ec7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_position_position_name', table_name='position')
    op.create_index(op.f('ix_position_position_name'), 'position', ['position_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_position_name'), table_name='position')
    op.create_index('ix_position_position_name', 'position', ['position_name'], unique=False)
    # ### end Alembic commands ###
