"""statistics tables

Revision ID: e7a888a3a1b2
Revises: 45fcf2f2c14a
Create Date: 2021-01-07 20:27:35.030800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a888a3a1b2'
down_revision = '45fcf2f2c14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batter_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('exit_speed', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('hit_spin_rate', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitcher_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('auto_pitch_type', sa.String(length=64), nullable=True),
    sa.Column('pitch_call', sa.String(length=64), nullable=True),
    sa.Column('rel_speed', sa.Float(), nullable=True),
    sa.Column('vert_rel_angle', sa.Float(), nullable=True),
    sa.Column('horz_rel_angle', sa.Float(), nullable=True),
    sa.Column('spin_rate', sa.Float(), nullable=True),
    sa.Column('spin_axis', sa.Float(), nullable=True),
    sa.Column('tilt', sa.Float(), nullable=True),
    sa.Column('rel_height', sa.Float(), nullable=True),
    sa.Column('rel_side', sa.Float(), nullable=True),
    sa.Column('extension', sa.Float(), nullable=True),
    sa.Column('vert_break', sa.Float(), nullable=True),
    sa.Column('induced_vert_break', sa.Float(), nullable=True),
    sa.Column('horz_break', sa.Float(), nullable=True),
    sa.Column('plate_loc_size', sa.Float(), nullable=True),
    sa.Column('plate_loc_height', sa.Float(), nullable=True),
    sa.Column('vert_appr_angle', sa.Float(), nullable=True),
    sa.Column('horz_appr_angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitcher_record')
    op.drop_table('batter_record')
    # ### end Alembic commands ###
